/* autogenerated by Processing revision 1292 on 2023-03-01 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Figuren2 extends PApplet {

public void zeichneBildC(){
    rect(10,10,100,100); //äußeres Rechteck
    ellipse(60, 170, 100, 100); //äußere Ellipse
    for(int i = 0; i < 3; i++){ // 3x Loop
        ellipse(60, 60, 80-i*20, 80-i*20); // innere Ellipsen
        rect(30+i*10,140+i*10,60-i*20,60-i*20); // innere Rechtecke
    }
}
public void setup(){
    /* size commented out by preprocessor */;
    zeichneBildC();
}


  public void settings() { size(600, 600); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Figuren2" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
